language: python
group: travis_latest
dist: xenial

git:
  depth: 25
  quiet: true

env: FC=gfortran-6

addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages: ['gfortran-6','liblapack-dev','libmumps-dev','libopenmpi-dev']

# works on osx, but Azure is faster
#    - brew install gcc
#    - brew install lapack openblas open-mpi scalapack
#    - brew tap dpo/openblas
#    - brew install mumps

before_install:
- git clone https://github.com/mesonbuild/meson ../meson
- python -m pip install -e ../meson
- curl -Ls https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-linux.zip -o ninja-linux.zip
- sudo unzip ninja-linux.zip -d /usr/local/bin/

install: meson build

script: meson test -C build --suite unit
