runs:

  using: "composite"

  steps:

  - name: Configure multi
    shell: bash
    run: $CMAKE --preset multi -Dhwm14:BOOL=${{ matrix.hwm14 }}

  - name: Upload log failure
    if: failure()
    uses: actions/upload-artifact@v6
    with:
      name: ${{ env.CC }}-${{ env.FC }}-${{ runner.os }}-CMakeConfigureLog.yaml
      path: build/CMakeFiles/CMakeConfigureLog.yaml


  - name: Debug build
    shell: bash
    run: $CMAKE --build --preset debug

  - name: Debug unit test
    shell: bash
    run: $CTEST --preset debug -L unit

  # - name: Debug core test
  #   shell: bash
  #   run: $CTEST --preset debug -LE unit -R "(2dew_.*fang|2dns_.*fang)"


  - name: Release build
    shell: bash
    run: $CMAKE --build --preset release

  - name: Release unit test
    shell: bash
    run: $CTEST --preset release -L unit

  - name: Release core test
    shell: bash
    run: $CTEST --preset release -LE unit -R "(2dew_.*fang$|2dns_.*fang$)"

    # run: $CTEST --preset release -LE unit -E 3d
