name: ci_linux
env:
  CI: true

on:
  push:
    paths:
      - "**.f90"
      - "**.F90"
      - "**.cmake"
      - "**.build"
      - "**.txt"
      - ".github/workflows/ci_linux.yml"
  pull_request:
    paths:
      - "**.f90"
      - "**.F90"
      - "**.cmake"
      - "**.build"
      - "**.txt"
      - ".github/workflows/ci_linux.yml"

jobs:

  cmakeHDF5:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - run: python3 -m pip install -e .[tests]
    - name: Install packages
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends pkg-config gfortran libopenmpi-dev openmpi-bin liblapack-dev libscalapack-openmpi-dev libmumps-dev libhdf5-dev libpthread-stubs0-dev
        pip install cmake

    - name: CMake configure
      run: cmake -B build -Dhdf5=true
      env:
        FC: gfortran
    - run: cmake --build build --parallel
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: LinuxOS_Cmake_Buildlog
        path: build/CMakeFiles/CMakeError.log
# CI is too slow for 3d_glow

# -V output truncated on CI?
    - run: ctest --parallel --output-on-failure -E 3d_glow
      working-directory: build
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Linux_CMake_Testlog
        path: build/Testing/Temporary/LastTest.log

  mesonHDF5:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - run: pip install -e .[tests]
    - name: Install packages
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends ninja-build pkg-config gfortran libopenmpi-dev openmpi-bin liblapack-dev libscalapack-openmpi-dev libmumps-dev libhdf5-dev

    - run: meson setup build -Dhdf5=enabled
      env:
        FC: gfortran
    - run: ninja -C build
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Linux_Meson_Buildlog
        path: build/meson-logs/meson-log.txt

    - run: meson test -C build --suite unit -v
    - run: meson test -C build --suite 2d_fang -v
    - run: meson test -C build --suite 2d_glow -v
# CI is too slow for 3d_glow
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Linux_Meson_Testlog
        path: build/meson-logs/testlog.txt
