name: ci_rawio
# for non-HDF5 I/O

env:
  CI: true

on:
  release

jobs:

  cmake:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: python3 -m pip install -e .[tests]
    - name: Install packages
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends gfortran libopenmpi-dev openmpi-bin liblapack-dev libscalapack-mpi-dev libmumps-dev libpthread-stubs0-dev
        pip install cmake

    - name: CMake configure
      run: cmake -B build -Dhdf5=disabled
      env:
        FC: gfortran
    - run: cmake --build build --parallel
# CI is too slow for 3d_glow
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: LinuxRawIO_Cmake_Buildlog
        path: build/CMakeFiles/CMakeError.log

# -V output truncated on CI?
    - run: ctest --parallel --output-on-failure -E 3d_glow
      working-directory: build
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: LinuxRawIO_CMake_Testlog
        path: build/Testing/Temporary/LastTest.log

  meson:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: |
        pip install -e .[tests]
        pip install meson
    - name: Install packages
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends ninja-build pkg-config gfortran libopenmpi-dev openmpi-bin liblapack-dev libscalapack-mpi-dev libmumps-dev

    - run: meson setup build -Dhdf5=disabled
      env:
        FC: gfortran
    - run: ninja -C build
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: LinuxRawIO_Meson_Configlog
        path: build/meson-logs/meson-log.txt

    - run: meson test -C build --suite unit -v
    - run: meson test -C build --suite 2d_fang -v
    - run: meson test -C build --suite 2d_glow -v
# CI is too slow for 3d_glow
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: LinuxRawIO_Meson_Testlog
        path: build/meson-logs/testlog.txt